# Generated by Django 6.1.1 on 2026-10-03 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField(verbose_name='Problem description')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Condition notes')),
                ('diagnosis', models.TextField(blank=True, verbose_name='Diagnosis')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('diagnosis', 'Diagnosis'), ('waiting_approval', 'Waiting for approval'), ('waiting_parts', 'Waiting for parts'), ('in_progress', 'In progress'), ('ready', 'Ready for pickup'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='accepted', max_length=30, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('quote_version', models.PositiveIntegerField(default=1, verbose_name='Quote version')),
                ('approved_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='Approved version')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved at')),
                ('approval_method', models.CharField(blank=True, choices=[('phone', 'Phone'), ('messenger', 'Messenger'), ('email', 'Email'), ('in_person', 'In person')], max_length=20, verbose_name='Approval method')),
                ('quality_check_notes', models.TextField(blank=True, verbose_name='Quality check notes')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid at')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_orders', to='customers.bicycle', verbose_name='Bicycle')),
            ],
            options={
                'verbose_name': 'repair order',
                'verbose_name_plural': 'repair orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='orders_repa_status_8f9bd8_idx'), models.Index(fields=['deadline'], name='orders_repa_deadlin_7fc61b_idx')],
            },
        ),
    ]
