# Generated by Django 6.1.1 on 2026-10-02 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Full name')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Brand')),
                ('model', models.CharField(max_length=100, verbose_name='Model')),
                ('bike_type', models.CharField(choices=[('city', 'City bike'), ('mountain', 'Mountain bike'), ('road', 'Road bike'), ('gravel', 'Gravel bike'), ('hybrid', 'Hybrid bike'), ('touring', 'Touring bike'), ('bmx', 'BMX'), ('fat', 'Fat bike'), ('folding', 'Folding bike'), ('cargo', 'Cargo bike'), ('kids', "Kids' bike"), ('other', 'Other')], default='other', max_length=20, verbose_name='Type')),
                ('frame_number', models.CharField(blank=True, max_length=100, verbose_name='Frame number')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bicycles', to='customers.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'bicycle',
                'verbose_name_plural': 'bicycles',
                'ordering': ['brand', 'model'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('frame_number', ''), _negated=True), fields=('frame_number',), name='unique_frame_number_if_set')],
            },
        ),
    ]
