# Generated by Django 6.1.1 on 2026-10-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('sku', models.CharField(max_length=100, unique=True, verbose_name='SKU')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stock quantity')),
                ('minimum_stock', models.PositiveIntegerField(default=0, verbose_name='Minimum stock')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'part',
                'verbose_name_plural': 'parts',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('purchase_price__gte', 0)), name='part_purchase_price_gte_0'), models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='part_selling_price_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Base price')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('base_price__gte', 0)), name='service_base_price_gte_0')],
            },
        ),
    ]
